<a href="https://colab.research.google.com/github/HomayounSoleimani/Python-for-Machine-Learning-and-Artificial-Neural-Networks/blob/master/1_01_SVM_classifier_on_Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Predicting wether a customer has exited from the bank or he/she is still a member of the bank.
for this problem we have made use of svm stands for support vector machine.

**Import libraries and data**

In [0]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
X_data = dataset.iloc[:, 3:-1]
X_data.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

**Categorical to numerical labeling**

In [6]:
# Using labelEncoder
le = LabelEncoder()
X_data["Geography"] = le.fit_transform(dataset["Geography"])
X_data["Gender"] = le.fit_transform(dataset["Gender"])
X_data.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

**Scaling**

In [12]:
# Using StandardScaler
scaler = StandardScaler()
X_data = scaler.fit_transform(X_data) # Returns numpy array.
X_data[:2] # First two observations

array([[-0.32622142, -0.90188624, -1.09598752,  0.29351742, -1.04175968,
        -1.22584767, -0.91158349,  0.64609167,  0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752,  0.19816383, -1.38753759,
         0.11735002, -0.91158349, -1.54776799,  0.97024255,  0.21653375]])

In [14]:
# Getting y_data
Y_data = dataset["Exited"].values
Y_data[0:2] # First two target

array([1, 0])

**Splitting data to train and test**

In [15]:
x_train, x_test, y_train, y_test = train_test_split(X_data, Y_data)
x_train[0:5]

array([[-0.64697147, -0.90188624, -1.09598752, -1.13678644,  1.03290776,
        -1.22584767, -0.91158349,  0.64609167, -1.03067011, -1.39153496],
       [ 1.09128685, -0.90188624,  0.91241915, -0.75537207,  1.72446358,
         0.73983427, -0.91158349, -1.54776799, -1.03067011, -0.66814401],
       [-1.19535058,  1.51506738,  0.91241915, -0.18325053, -0.69598177,
         1.58746735,  0.80773656,  0.64609167,  0.97024255, -1.57976846],
       [ 0.7291497 ,  0.30659057,  0.91241915,  0.10281024,  0.34135195,
         0.38128477, -0.91158349,  0.64609167, -1.03067011,  0.66902859],
       [ 0.52221419, -0.90188624,  0.91241915, -1.5182008 , -0.69598177,
        -1.22584767,  0.80773656,  0.64609167, -1.03067011, -1.06298353]])

In [16]:
y_train[0:5]

array([0, 0, 0, 1, 0])

**Define classifier**

In [21]:
classifier = SVC(gamma=0.02)
classifier.fit(x_train, y_train)

print("Sccuracy score on training set is {:.3f}".format(classifier.score(x_train,y_train)))
print("Sccuracy score on testing set is {:.3f}".format(classifier.score(x_test, y_test)))

Sccuracy score on training set is 0.846
Sccuracy score on testing set is 0.855
